#+TITLE: PSEUDOCODE
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE:CSC100 Introduction to programming in C/C++ (Spring 2023)
#+STARTUP: overview hideblocks indent inlineimages
#+OPTIONS: toc:1 ^:nil
#+PROPERTY: header-args:C :main yes :includes <stdio.h> :exports both :results output :noweb yes :tangle yes
* README

- In this section of the course, we go beyond simple statements and
  turn to program flow and evaluation of logical conditions

- This section follows chapter 3 in Davenport/Vine (2015) and
  chapters 4 and 5 in King (2008)

- Practice workbooks, input files and PDF solution files in GitHub

* Pseudocode
* Overview

- *Pseudocode* is a method to write down/analyze an /algorithm/ or a
  /heuristic/ without having to bother with /syntax/

- The prefix pseudo- comes from Ancient Greek [[https://en.wiktionary.org/wiki/%CF%88%CE%B5%CF%85%CE%B4%CE%AE%CF%82][ψευδής]], meaning
  "lying", "false" or "untrue", as in "pseudoscience" or "pseudonym"

- Pseudocode does not need to compile or run so it is closer to a
  heuristic than to an exact algorithm.

- Code however needs to be exact and is always algorithmic

* Example

- Example: player problem statement in [[problem1]] below:

  #+name: problem1
  #+begin_quote
  "Drink a health potion when a character's health is 100 or
  less. If health reaches 100 or more, resume battle."
  #+end_quote

- Given the problem [[problem1]], this is the pseudocode [[pseudocode1]][fn:1]:

  #+name: pseudocode1
  #+begin_example C
  if health is less than 100
    Drink health potion
  else
    Resume battle
  end if
  #+end_example

- The code in [[pseudocode1]] would not compile as a C program (you can
  test yourself: which mistakes would the compiler find?[fn:2])

- The conceptual "trick" with generating pseudocode from a prose
  description is to identify the *logical condition* so that you can
  perform a comparison (= apply a *conditional operator*)

- The pseudocode [[pseudocode1]] leads to the condition ~health < 100~:

  #+name: pseudocode11
  #+begin_example C
  if health < 100
    Drink health potion
  else
    Resume battle
  end if
  #+end_example

- Notice that you could also use another operator: ~>=~ This operator
  would have had the same effect but it is not what you were
  supposed to code.

  #+name: pseudocode12
  #+begin_example C
  if health >= 100
    Resume battle
  else
    Drink health potion
  end if
  #+end_example

- *Rule:* when making models (via *abstraction*), always stay as close
  to the problem description as possible - in terms of language,
  logic, tone, etc. If you're unsure, ask.

* Let's practice!

Get the practice file from GitHub:

#+begin_src bash :results silent
  wget tinyurl.com/prsmbhvh -O pseudo.org -o log
#+end_src

* Footnotes

[fn:1]In Org mode, you can use the language as an example header
argument to enable syntax highlighting. For pseudocode, this will of
course not work perfectly, since most syntax elements are not in C.

[fn:2]Undeclared variable ~health~, missing closure semi-colons after
the statements, functions ~Drink~ and ~Resume~ not known, and more.

